name: 🐛 Bug Report
description: Report a bug in client
title: '[BUG]'
labels: ['bug', 'needs-triage']
assignees: ['HMAZonderland']

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the sections below.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have tested with the latest version
          required: true

  - type: input
    id: version
    attributes:
      label: Package version
      description: Which version of this package are you using?
      placeholder: '1.0.0'
    validations:
      required: true

  - type: dropdown
    id: config-type
    attributes:
      label: Component type
      description: Which component or feature is affected?
      options:
        - Core functionality
        - API interface
        - TypeScript types
        - Build/bundling
        - Testing
        - Documentation
        - Dependencies
        - Configuration
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide your environment details
      value: |
        - Node.js version:
        - Package version:
        - TypeScript version:
        - Operating System:
      render: markdown
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: A clear description of the bug
      placeholder: Describe what happened and what you expected
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the issue
      placeholder: |
        1. Install with pnpm install
        2. Run pnpm dev or pnpm build
        3. Execute specific command
        4. See error
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code sample
      description: Minimal code that reproduces the issue
      render: typescript
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other relevant information
    validations:
      required: false
