name: 🚀 Feature Request
description: Suggest a new feature or enhancement for client
title: '[FEATURE]'
labels: ['enhancement', 'needs-triage']
assignees: ['HMAZonderland']

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Help us understand what enhancement you need.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues for similar requests
          required: true
        - label: This feature would benefit the broader community
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature type
      description: What type of feature is this?
      options:
        - Core functionality
        - API enhancement
        - Developer experience
        - Performance improvement
        - Build/tooling integration
        - Documentation
        - Testing
        - CI/CD workflow
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem description
      description: What problem does this feature solve?
      placeholder: Describe the current limitation or pain point
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this feature work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other solutions did you consider?
      placeholder: Describe alternative approaches you've thought about
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use cases
      description: Provide specific examples of how this would be used
      placeholder: |
        1. When working on...
        2. Developers could...
        3. This would help with...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation ideas
      description: Any thoughts on how this could be implemented?
      placeholder: Optional implementation suggestions
    validations:
      required: false

  - type: checkboxes
    id: willing-to-contribute
    attributes:
      label: Contribution
      options:
        - label: I am willing to help implement this feature
        - label: I can provide additional details if needed
