name: ❓ Question
description: Ask a question about usage, configuration, or best practices
title: '[Question]:'
labels: ['question', 'needs-triage']
assignees: ['HMAZonderland']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! Please provide as much context as possible to help us give you the best answer.

  - type: textarea
    id: question
    attributes:
      label: ❓ Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 📂 Category
      description: What category does your question fall into?
      options:
        - Usage - How to use the package or specific features
        - Configuration - Setting up or configuring the package
        - Integration - Integrating with other tools or frameworks
        - Performance - Performance optimization or troubleshooting
        - Best Practices - Recommended approaches or patterns
        - Troubleshooting - Debugging issues or unexpected behavior
        - API - Understanding the API or method signatures
        - Examples - Looking for code examples or tutorials
        - Other - Something else
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 🔍 Context
      description: Provide more context about what you're trying to accomplish.
      placeholder: |
        What are you trying to build or achieve?
        What have you tried so far?
        What specific challenges are you facing?

  - type: textarea
    id: code
    attributes:
      label: 💻 Current code (if applicable)
      description: Share any relevant code you're working with.
      placeholder: |
        ```typescript
        // Your current code here
        ```
      render: typescript

  - type: textarea
    id: environment
    attributes:
      label: 🔧 Environment (if relevant)
      description: |
        If your question is environment-specific, please provide details:
      value: |
        - OS: [e.g. macOS 14.0, Windows 11, Ubuntu 22.04]
        - Browser: [e.g. Chrome 120, Firefox 121, Safari 17]
        - Node.js: [e.g. 18.17.0, 20.9.0]
        - Package Manager: [e.g. npm 9.8.1, pnpm 8.10.0]
        - Package Version: [e.g. @virtualdisplay-io/client@2.3.0]
        - Framework: [e.g. React 18, Vue 3, Vanilla JS]

  - type: dropdown
    id: urgency
    attributes:
      label: ⏰ Urgency
      description: How urgent is this question for you?
      options:
        - Low - Just curious, no rush
        - Medium - Would help with current development
        - High - Blocking my current work
    validations:
      required: true

  - type: checkboxes
    id: research
    attributes:
      label: 🔎 Research done
      description: What have you already tried to find the answer?
      options:
        - label: I have read the documentation
        - label: I have searched existing issues and discussions
        - label: I have looked at the examples in the repository
        - label: I have tried searching online for similar questions

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: This is a question, not a bug report or feature request
          required: true
        - label: I have provided sufficient context for my question
          required: true
        - label: I have searched for existing answers to similar questions
          required: true

  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional information
      description: Any other details that might help us understand your question better.
      placeholder: |
        - Links to relevant documentation
        - Screenshots of error messages
        - Related issues or discussions
        - Specific use case details
