name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    timeout-minutes: 3

    steps:
      - name: Check if PR is auto-mergeable
        id: check-automerge
        run: |
          # Get PR details
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_LABELS="${{ join(github.event.pull_request.labels.*.name, ' ') }}"

          # Check if this is a safe dependency update
          if [[ "$PR_TITLE" =~ ^deps.*development-dependencies ]] || \
             [[ "$PR_TITLE" =~ ^deps.*testing-dependencies ]] || \
             [[ "$PR_TITLE" =~ ^deps.*build-dependencies ]] || \
             [[ "$PR_TITLE" =~ ^ci: ]] || \
             [[ "$PR_LABELS" =~ automated ]]; then
            echo "auto_merge=true" >> $GITHUB_OUTPUT
            echo "This PR is eligible for auto-merge"
          else
            echo "auto_merge=false" >> $GITHUB_OUTPUT
            echo "This PR requires manual review"
          fi

      - name: Wait for CI checks
        if: steps.check-automerge.outputs.auto_merge == 'true'
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-checks
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: 'Test'
          ref: ${{ github.event.pull_request.head.sha }}
          timeoutSeconds: 600
          intervalSeconds: 15

      - name: Auto-approve PR
        if: steps.check-automerge.outputs.auto_merge == 'true' && steps.wait-for-checks.outputs.conclusion == 'success'
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve --body "Auto-approved by Dependabot workflow: safe dependency update detected."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        if: steps.check-automerge.outputs.auto_merge == 'true' && steps.wait-for-checks.outputs.conclusion == 'success'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add comment for manual review
        if: steps.check-automerge.outputs.auto_merge == 'false'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "🔍 This dependency update requires manual review before merging."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
